server:
  port: 8001
debug: true
spring:
  application:
    name: playment-service
  datasource: #连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: kang
    druid:
      max-active: 20
      min-idle: 1
      max-wait: 6000
      initial-size: 1
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.sunkang.orderservcie.entity

#注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 单机版
      defaultZone: http://user:kang@localhost:7001/eureka
      #集群版
      #defaultZone: http://user:kang@eureka7001.com:7001/eureka,http://user:kang@eureka7002.com:7002/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 #心跳时间
    lease-expiration-duration-in-seconds: 90 #发呆时间
#监控
management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    info:
      enabled: true
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。