server:
  port: 80
# 日志级别
logging:
  level:
    # 打印fegin日志需要将项目日志级别设置为debug
    com.sunkang.orderservice.feign: debug
spring:
  application:
    name: order-service

payment:
  address: http://playment-service/

#注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 单机版
      defaultZone: http://user:kang@localhost:7001/eureka
      #集群版
      #defaultZone: http://user:kang@eureka7001.com:7001/eureka,http://user:kang@eureka7002.com:7002/eureka
    healthcheck:
      enabled: true
  instance:
    instance-id: order80 #实例名
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 #心跳时间
    lease-expiration-duration-in-seconds: 90 #发呆时间
#监控
management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    info:
      enabled: true

#设置feign超时时间
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000

#feign开启hystrix
feign:
  hystrix:
    enabled: true
#hystrix超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

