server:
  port: 9002
spring:
  application:
    name: hystrix-turbine
#注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 单机版
      defaultZone: http://user:kang@localhost:7001/eureka
      #集群版
      #defaultZone: http://user:kang@eureka7001.com:7001/eureka,http://user:kang@eureka7002.com:7002/eureka
    healthcheck:
      enabled: true
  instance:
    instance-id: hystrix9002 #实例名
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 #心跳时间
    lease-expiration-duration-in-seconds: 90 #发呆时间
turbine:
  app-config: order-service,playment-service
  cluster-name-expression: "'default'"
management:
  endpoints:
    web:
      exposure:
        include: '*'