server:
  port: 8001
payment:
  addr: http://alibaba-payment

management:
  endpoint:
    web:
      exposure:
        include: '*'
debug: true
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1



